### PR TITLE
Update DescriptionSection.js

### PR DESCRIPTION
**Pull request by Walter-Haydock**
Fixed typo ("cryptogrpahic - > "cryptographic")

### CODE REVIEW

**Comment by mattgreg** [comment]
Hi @Walter-Haydock changes look great - good catch!
Thank you for sending the PR :heart:
Before we can merge, a couple of small requests:
1. Could you sign the commit
2. Could you accept our CLA.
Read the CLA at  
https://www.ockam.io/learn/how-to-guides/contributing/cla/
To accept the CLA please send a different PR to our contributors repo indicating that you accept the CLA by adding your Git/Github details in a row at the end of the CONTRIBUTORS.csv file:  
https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv
Looking forward to merging your first contribution!!

**Comment by Walter-Haydock** [comment]
@mattgreg - I have accepted the CLA. Regarding signing the commit, do you mean with my own GPG (or other) key? If so, I have been having some trouble submitted a signed PR. Any resources you might suggest to consult?

**Comment by Walter-Haydock** [comment]
I had to open another PR, but I think I got it. Please confirm that this answers the mail: https://github.com/ockam-network/website/pull/460.

**Comment by mrinalwadhwa** [comment]
@Walter-Haydock on GPG signing, new comers on our team use Krypton, check it out - its a little more convenient
https://krypt.co/docs/start/code-signing.html

**Comment by Walter-Haydock** [comment]
Completing this via https://github.com/ockam-network/website/pull/460

**Pull request closed without merging**
