### PR TITLE
fix: broken links

### PR DESCRIPTION
**Pull request by njvrzm**
I wanted to look at your engineering levels page, but the link is broken. Then I found some more broken links. Then I wrote a little scraper to find them all :) Then I fixed them - most of them, anyway. There are a few that have slightly more complex problems that I'll open issues for.

### CODE REVIEW

**Comment by njvrzm** [comment]
Ironically, I don't think I'll be able to sign the CLA before this is merged, because the `cla.yml` is one of the places with a broken link.

**Comment by Necromos** [comment]
recheckcla

**Comment by mattgreg** [comment]
@njvrzm Since our CLA Check bot has a bug and is blocking the merge here, I've sent you a Docusign as an alternative to this automated flow. Once you sign the Docusign we can manually merge this contribution. Thanks for the patience

**Comment by mattgreg** [comment]
Thanks @njvrzm

**Comment by miedziak** [comment]
@njvrzm @mattgreg I have re-created this PR with updated upstream and changed target branch. Please take a look #346

**Comment by mattgreg** [comment]
duplicate. closed

**Pull request closed without merging**
