### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by suraj142**
Corrected grammatical error in a sentence.

### CODE REVIEW

**Comment by mattgreg** [comment]
@surajphulara I'd love to accept your PR. A couple things:

You need to sign the CLA in this thread and your PR needs to conform to our commit format (no upper case letters). Also use the present tense (not updated). something like `content: fix grammer in readme` would work.

**Comment by surajphulara** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mattgreg** [comment]
recheckcla

**Comment by surajphulara** [comment]
recheckcla

**Comment by mattgreg** [comment]
@surajphulara I'd like to merge your PR and close it. Can you rebase and be sure that the CI passes so I can do so...

**Comment by surajphulara** [comment]
> @surajphulara I'd like to merge your PR and close it. Can you rebase and be sure that the CI passes so I can do so...

How to make it pass CI

**Comment by mattgreg** [comment]
@suraj142 all you need to do is rebase and merge to the latest `develop`

**Comment by mrinalwadhwa** [comment]
@suraj142 thank you for the contribution.

I cherry-picked and merged your changes, with some minor changes to the commit message to follow our conventions.
Made sure your attribution is maintained. https://github.com/ockam-network/website/commit/731b88db08730af97d00337df3b8ba58866af809

**Pull request closed without merging**
