### PR TITLE
feat: CLI for project

### PR DESCRIPTION
**Pull request by sobi3ch**
* Add internal CLI for project setup

Resolves: OCM-6

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@sobi3ch could you resolve conflicts with develop so this is rebase-able.

**Comment by sobi3ch** [comment]
> @sobi3ch could you resolve conflicts with develop so this is rebase-able.

@mrinalwadhwa now should be ok, please check it

**Comment by mrinalwadhwa** [comment]
@sobi3ch could you amend the commit message to follow this please
https://www.conventionalcommits.org/en/v1.0.0-beta.4/

**Comment by sobi3ch** [comment]
@mrinalwadhwa sorry for that, it's amended now

**Comment by mrinalwadhwa** [comment]
@sobi3ch thank you for making the changes, another merge caused a conflict, could you please resolve it. I'll merge after that.

**Comment by sobi3ch** [comment]
@mrinalwadhwa done, thank you

**Pull request merged**
