### PR TITLE
content: fix typo

### PR DESCRIPTION
**Pull request by winmillwill**
This doc was a great read! This small typo jumped out at me and seems like an easy fix.

### CODE REVIEW

**Comment by mattgreg** [comment]
Thanks for submitting this PR!

We have a commit message format: https://www.ockam.io/learn/guides/contributions/CONTRIBUTING/#commit-messages

can you change the commit message to ```content: fix typo```??

**Comment by winmillwill** [comment]
Thanks for the pointer. Fixed!

**Comment by mattgreg** [comment]
recheckcla

**Comment by mattgreg** [comment]
Hey @winmillwill we have a brand new CLA workflow! Can you complete the CLA GitHub action instructions above?

**Comment by winmillwill** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mattgreg** [comment]
recheckcla

**Comment by mattgreg** [comment]
@winmillwill You are the first test user! You didn't know this little typo fix would be so impactful I bet.

From your post 2 hours ago we learned that a reply via email doesn't trigger the GitHub action. I've made a note of the issue.

Can you try again by opening your web browser and attempting to trigger the github action in a new comment?

❤️ 🙌

Also, DM me a mailing address and I'll send you one of our Ockam hats!

**Comment by winmillwill** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mattgreg** [comment]
That worked!  Thanks for the persistence. 

https://github.com/ockam-network/contributors/blob/master/cla-signers.json

**Pull request closed without merging**
