### PR TITLE
fix typo in values and virtues guide

### PR DESCRIPTION
**Pull request by franziskuskiefer**
There's a double "then"

### CODE REVIEW

**Comment by jared-s** [comment]
Thanks for catching that @franziskuskiefer! I'll branch this and get it through our CI process.

**Comment by jared-s** [comment]
@franziskuskiefer before we merge this, would you mind reading and accepting our Contributor License Agreements (CLA), and adding yourself to our Contributors list?

You can find the CLA here: https://www.ockam.io/learn/how-to-guides/contributing/cla/

After reading that, please open a PR to our [contributors](https://github.com/ockam-network/contributors) repo and add a row for yourself in this file: https://github.com/ockam-network/contributors/blob/main/CONTRIBUTORS.csv

Thanks again!

**Comment by jared-s** [comment]
After we get the CLA sorted, there's just a few other things:

- Could you please change the target of the PR to the `develop` branch?
- Could you change the commit message to begin with 'docs: ' - we have a strict convention for tagging commits

Thanks!

**Comment by franziskuskiefer** [comment]
I filed https://github.com/ockam-network/contributors/pull/6

**Comment by jared-s** [comment]
Merged as https://github.com/ockam-network/website/pull/382. Thank you!

**Pull request closed without merging**
