### PR TITLE
fix: s/heros/heroes/

### PR DESCRIPTION
**Pull request by vvv**
Heros is a fish.

### CODE REVIEW

**Comment by vvv** [comment]
https://www.ockam.io/learn/guides/contributions/CONTRIBUTING/#contributor-license-agreement-cla:
> When you submit a Pull Request, a bot will ask you to sign our CLA if you haven't done so before.

Well, it didn't.

https://www.ockam.io/learn/guides/contributions/CONTRIBUTING/#commit-messages:
> **Ockam requires that all commits are signed by your PGP key.**

I did sign my commit.
```
$ git log -1 --show-signature
commit 704f06863df4e753921f078a76ac4cf44e096a3c
gpg: Signature made Thu Aug 27 12:17:32 2020 EEST
gpg:                using RSA key 698B6D033F5C5A78A9670DAB744626755CC81140
gpg: Good signature from "Valery V. Vorotyntsev <valery.vv@gmail.com>" [ultimate]
Author: Valery V. Vorotyntsev <valery.vv@gmail.com>
Date:   Thu Aug 27 11:41:01 2020 +0300

    fix: s/heros/heroes/
    
    Heros is a fish.
```

> * In GitHub, send a pull request to `ockam:develop`.

This is a tad confusing.  Suggestion:
```
s/`ockam:develop`/the `develop` branch/
```

> * The Ockam Contributor License Agreement tool will check to see if you've signed our CLA. If you have not yet done so, the PR will be blocked. The fix is easy. Simply click the link in the PR 'Conversation' user experience on github.com and follow the signing steps.

I cannot understand the last sentence.  Does it mean "Click 'Conversation' tab on the pull request page and follow the signing steps."?

cc @mrinalwadhwa

**Comment by vvv** [comment]
Can someone help me overcome the CLA Check error please?

**Comment by vvv** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by mattgreg** [comment]
You found (one of) my easter eggs in the website! Thanks for the PR. This is awesome. You made my day.

[Heroes](https://www.youtube.com/watch?v=lXgkuM2NhYI)

**Comment by vvv** [comment]
> You found (one of) my easter eggs in the website!

@mattgreg Good one!👨🏻‍🎤 

Should we close this PR unmerged then?

**Comment by mattgreg** [comment]
We will merge it!

**Comment by mrinalwadhwa** [comment]
@vvv thanks for the feedback on the CLA flow, we turned it on only a few weeks ago so your experience provides so great feedback an things to improve

**Comment by miedziak** [comment]
@vvv please rebase to `ockam-network:develop` before merge

**Pull request merged**
